### ISSUE TITLE
Potential vulnerability

### ISSUE THREAD

**Issue by amatsagu** [UnintendedFraud/hal#1]
Hey, I've seen your having a key/token "hard coded" inside your ["psg" command source code](https://github.com/UnintendedFraud/hal/blob/main/commands/psg.go#L58) .

**Comment by UnintendedFraud** [comment]
Hey, thank you! Indeed I accidentally pushed a private key (no real harm thankfully), fixed it. Allowed me to learn about modifying a git history, you win or you learn as they say.

Thanks
